spring:
  application:
    name: consumer
  kafka:
    consumer:
      auto-offset-reset: earliest
      client-id: ${spring.application.name}-${random.value}
      group-id: test-consumers-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

app:
  kafka:
    retry-max-attempts: 3
    retry-back-off-period: 2000
    recover-max-attempts: 2
    recover-back-off-period: 7000
    topics:
      data: data
